<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Biblioteca</title>
    
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="home">Inicio</a>
                </li>
                <li>
                    <a href="tabla">Libros</a>
                </li>
                <li>
                    <a href="login">Login</a>
                </li>
            </ul>
        </nav>
    </header>
</body>

</html>